{"name": "Ошибка 400 Bad Request при запросе на получение делатей заказа без номера заказа.", "status": "passed", "description": "Отправляем GET запрос на ручку /api/v1/orders/track?t= без номера заказа. Проверяем что ответ 400 Bad Request и сообщение в теле ответа \"Недостаточно данных для поиска\"", "steps": [{"name": "GET request.", "status": "passed", "parameters": [{"name": "path", "value": "'/api/v1/orders/track?t='"}], "start": 1738945779398, "stop": 1738945779449}], "start": 1738945779398, "stop": 1738945779449, "uuid": "a54278dc-2158-4cd3-b2ea-c671090b558c", "historyId": "bc5c2ee3fc3baeb7ed70df3324909d27", "testCaseId": "bc5c2ee3fc3baeb7ed70df3324909d27", "fullName": "tests.test_get_order_by_number.TestGetOrderByNumber#test_get_order_by_number_no_order_number_shows_error_400", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_number"}, {"name": "subSuite", "value": "TestGetOrderByNumber"}, {"name": "host", "value": "k-julls"}, {"name": "thread", "value": "14568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_number"}]}