{"name": "Ошибка 404 Not Found при запросе на получение делатей заказа с несуществующим номером заказа.", "status": "passed", "description": "Отправляем GET запрос на ручку /api/v1/orders/track?t= с несуществующим номером заказа. Проверяем что ответ 404 Not Found и сообщение в теле ответа \"Заказ не найден\"", "steps": [{"name": "Генерация рандомного ID", "status": "passed", "start": 1739134609021, "stop": 1739134609022}, {"name": "GET request.", "status": "passed", "parameters": [{"name": "path", "value": "'/api/v1/orders/track?t=537775550'"}], "start": 1739134609022, "stop": 1739134609066}], "start": 1739134609021, "stop": 1739134609067, "uuid": "5e3e0527-3308-4b4f-9e86-10d3a7572834", "historyId": "f848c349f17554318ff72181deb01b3d", "testCaseId": "f848c349f17554318ff72181deb01b3d", "fullName": "tests.test_get_order_by_number.TestGetOrderByNumber#test_get_order_by_number_not_valid_order_number_shows_error_404", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_number"}, {"name": "subSuite", "value": "TestGetOrderByNumber"}, {"name": "host", "value": "k-julls"}, {"name": "thread", "value": "10016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_number"}]}